services:
    dingdong-web:
        build:
            context: src/web/
        ports:
            - "5000:5000"
        env_file:
            - 'dingdong-example.env'
        environment:
            - DB_HOST=dingdong-db
    dingdong-db:
        build:
            context: src/db
        env_file:
            - 'dingdong-example.env'
